import_from_git(
  url: 'https://github.com/matteozero/fastlane.git',
  branch: 'master'
)

default_platform :ios

platform :ios do

  desc 'code analyze'
  lane :analyze do
    yk_analyze(workspace: 'Example/secp256k1.xcworkspace', scheme: 'secp256k1')
  end

  desc 'build dynamic framework'
  lane :build_fmk do
    yk_build_framework(project: 'secp256k1')
  end

  desc 'build static library'
  lane :build_lib do
    yk_build_static_lib(project: 'secp256k1')
  end

  desc 'publish source'
  lane :publish_src do |options|
    version = options[:version]
    yk_component_release_src(
      version:version,
      project:'secp256k1'
    )
  end

  desc 'publish static library'
  lane :publish_lib do |options|
    version = options[:version]
    yk_component_release_static_lib(
      version:version,
      project:'secp256k1'
    )
  end

  desc 'publish fmk'
  lane :publish_fmk do |options|
    version = options[:version]
    yk_component_release_fmk(
      version:version,
      project:'secp256k1'
    )
  end
end
